name: 'Check Deployment Status'
description: 'A simple GitHub Action for producing Jekyll build artifacts compatible with GitHub Pages'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  status_url:
    description: 'URL to query'
    required: true
  token: 
    description: 'GitHub token'
    required: true
  timeout:
    description: 'Number of one second timeouts'
    required: false
    default: 600